### ISSUE TITLE
"npm config set" in script not working

### ISSUE THREAD

**Issue by Kienz** [eprev/locationchanger#9]
I want to set specific npm configs if location changed. The script is running if the location changed but npm config ist not set.
If I run the script manuelly it works.

**Comment by eprev** [comment]
Some details would help.

**Comment by Kienz** [comment]
```
#!/usr/bin/env` bash

ts() {
    date +"[%Y-%m-%d %H:%M] $*"
}

# Work network location

# Proxy
ts 'Set proxy settings for Npm'
npm config --global set proxy http://example.com:8080/
npm config --global set https-proxy http://example.com:8080/
npm config --global set strict-ssl false

ts 'Set proxy settings for Git'
git config --global http.proxy http://example.com:8080/
git config --global https.proxy http://example.com:8080/
git config --global url."https://".insteadOf git://
```

The git config part works.
If I run the script manually both works.

**Comment by eprev** [comment]
If you add `exec 2>&1` below the hash-bang (this will forward stderr to stdout for the entire script), then you'll be able to see why it fails. Apparently, it's due to `npm` command cannot be found (the script is executed by `launchctl` and it might not have correct path to it in `$PATH`). So, if you're getting:

```
[...] Set proxy settings for Npm
...: npm: command not found
```

Then you can fix this by running `sudo launchctl config user path "/usr/local/bin:$PATH"` and then rebooting (where `/usr/local/bin` is the `dirname $(which npm)`).

**Comment by Kienz** [comment]
Thank you very much. After this it works!!
